/books:
    /{bookTitle}
      get:
        queryParameters:
          author:
          publicationYear:
          rating:
          isbn:
      put:
        queryParameters:
          access_token:
